name: Prepare Windows Build Environment
  
inputs:
  image:
    description: 'Docker Image'
    required: true
    default: 'ccl-win-base:latest'
  dockerargs:
    description: 'Additional Docker Arguments'
    required: false
    default: ''
  signkeyvault:
    description: 'Signing Key Vault'
    required: true
    default: ''
  signclientid:
    description: 'Signing Client ID'
    required: true
    default: ''
  signtenantid:
    description: 'Signing Tenant ID'
    required: true
    default: ''
  signcert:
    description: 'Signing Certificate'
    required: true
    default: ''
  signserver:
    description: 'Signing Key Serve'
    required: true
    default: ''  
  signsecret:
    description: 'Signing Secret'
    required: true
    default: ''
  
runs:
  using: "composite"
  steps:
    
    - name: Build CMake Target
      shell: bash
      run: |
        docker run \
          --volume "${{ github.workspace }}:F:" \
          --workdir "F:\\" \
          -e ccl_SIGNING_AZURE_KEYVAULT_WIN="${{ inputs.signkeyvault }}" \
          -e ccl_SIGNING_AZURE_CLIENTID_WIN="${{ inputs.signclientid }}" \
          -e ccl_SIGNING_AZURE_TENANTID_WIN="${{ inputs.signtenantid }}" \
          -e ccl_SIGNING_CERTIFICATE_WIN="${{ inputs.signcert }}" \
          -e ccl_SIGNING_TIMESTAMP_SERVER_WIN="${{ inputs.signserver }}" \
          -e ccl_SIGNING_AZURE_SECRET="${{ inputs.signsecret }}" \
          ${{ inputs.dockerargs }} \
          ghcr.io/cclsoftware/${{ inputs.image }} \
          bash ./.github/ci/win/build_cmake_target.sh
          