#!/usr/bin/env bash
set -euo pipefail

echo "CMAKE_BUILD_OPTIONS=-DSIGNING_TEAMID_MAC=$SIGNING_TEAMID_MAC -DSIGNING_TEAMID_IOS=$SIGNING_TEAMID_IOS -DSIGNING_CERTIFICATE_MAC=$SIGNING_CERTIFICATE_MAC -DVENDOR_CACHE_DIRECTORY=.cache/ccl" >> "$GITHUB_ENV"
