name: CCL SDK

concurrency:
  group: ccl-sdk
  
permissions:
  contents: read
  packages: read

on: 
  workflow_dispatch:
    inputs:
      buildWin:
        description: 'Build Windows SDK'
        type: boolean
        required: true
        default: true
      buildMac:
        description: 'Build Mac SDK'
        type: boolean
        required: true
        default: true
      buildLinux:
        description: 'Build Linux SDK'
        type: boolean
        required: true
        default: true

jobs:

  build-android-sdk:
    uses: ./.github/workflows/ccl-sdk-android.yml
    secrets: inherit

  build-linux-sdk:
    if: ${{ inputs.buildLinux }}
    needs: build-android-sdk
    uses: ./.github/workflows/ccl-sdk-linux.yml
    permissions:
      contents: read
      packages: read
    secrets: inherit
    
  build-windows-sdk:
    if: ${{ inputs.buildWin }}
    needs: build-android-sdk
    uses: ./.github/workflows/ccl-sdk-win.yml
    permissions:
      contents: read
      packages: read
    secrets: inherit
    
  # build-macos-sdk:
  #   if: ${{ inputs.buildMac }}
  #   needs: build-android-sdk
  #   uses: ./.github/workflows/ccl-sdk-mac.yml
  #   secrets: inherit
