name: CCL SDK for Windows

concurrency:
  group: ccl-sdk-win
  
on: workflow_call
  
jobs:
  build:
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: windows-2025
            image: ccl-win-sdk:latest
            targetos: win
            
    runs-on: ${{matrix.host}}
    
    permissions:
      contents: read
      packages: read
      
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
    
      - name: Setup CCL cache
        id: cache-ccl
        uses: actions/cache@v5
        with:
          path: .cache/ccl
          key: cclcache-${{ matrix.targetos }}-${{ github.ref_name }}
          
      - name: Prepare signing
        shell: bash
        run: |
          signfile="./build/signing/ccl/signing.cmake"
          echo 'set (SIGNING_AZURE_KEYVAULT_WIN "'"${{ secrets.SIGNING_AZURE_KEYVAULT_WIN }}"'")' >> "${signfile}"
          echo 'set (SIGNING_AZURE_CLIENTID_WIN "'"${{ secrets.SIGNING_AZURE_CLIENTID_WIN }}"'")' >> "${signfile}"
          echo 'set (SIGNING_AZURE_TENANTID_WIN "'"${{ secrets.SIGNING_AZURE_TENANTID_WIN }}"'")' >> "${signfile}"  
          echo 'set (SIGNING_CERTIFICATE_WIN "'"${{ secrets.SIGNING_CERTIFICATE_WIN }}"'")' >> "${signfile}"
          echo 'set (SIGNING_TIMESTAMP_SERVER_WIN "'"${{ vars.SIGNING_TIMESTAMP_SERVER_WIN }}"'")' >> "${signfile}"
          cat build/signing/ccl/signing.cmake
        
      - name: Fix signing
        shell: bash
        run: |
          cd framework
          git apply ../patches/windows-signing.patch
    
      - name: Log into registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Pull container
        shell: bash
        run: |
          docker pull ghcr.io/cclsoftware/${{matrix.image}}
              
      - name: Build in container
        shell: bash
        run: |
          docker run \
            --volume "${{github.workspace}}:F:" \
            --workdir "F:\\" \
            -e ccl_SIGNING_AZURE_SECRET="${{ secrets.SIGNING_AZURE_SECRET_WIN }}" \
            ghcr.io/cclsoftware/${{matrix.image}} \
            bash ./.github/ci/win/build_sdk.sh ${{github.run_number}}    
          
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ccl-sdk-${{matrix.targetos}}
          path: |
            build/cmake/archive/*.exe
