name: CCL SDK

concurrency:
  group: ccl-sdk
  
permissions:
  contents: read
  packages: read

on: 
  workflow_dispatch:
    inputs:
      buildWin:
        description: 'Build Windows SDK'
        type: boolean
        required: true
        default: true
      buildMac:
        description: 'Build Mac SDK'
        type: boolean
        required: true
        default: true
      buildLinux:
        description: 'Build Linux SDK'
        type: boolean
        required: true
        default: true

jobs:

  build-android-sdk:
    uses: ./.github/workflows/ccl-sdk-android.yml
    secrets: inherit

  build-in-docker:
    if: ${{ inputs.buildLinux == 'true' }}
    needs: build-android-sdk
    uses: ./.github/workflows/ccl-sdk-container.yml
    permissions:
      contents: read
      packages: read
    secrets: inherit
    
  build-for-win:
    if: ${{ inputs.buildWin == 'true' }}
    needs: build-android-sdk
    uses: ./.github/workflows/ccl-sdk-win.yml
    permissions:
      contents: read
      packages: read
    secrets: inherit
    
  build-macos-sdk:
    if: ${{ inputs.buildMac == 'true' }}
    needs: build-android-sdk
    uses: ./.github/workflows/ccl-sdk-mac.yml
    secrets: inherit