name: CCL SDK in Docker container

concurrency:
  group: ccl-sdk-container
  
on: workflow_call
  
jobs:
  build:
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: ubuntu-latest
            image: ccl-linux-sdk:22.04
            targetos: linux
            signbinaries: false
          #- host: windows-2025
          #  image: ccl-win-sdk:latest
          #  targetos: win
          #  signbinaries: true
            
    runs-on: ${{matrix.host}}
    
    permissions:
      contents: read
      packages: read
      
    container:
      image: ghcr.io/cclsoftware/${{matrix.image}}
      credentials:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
        
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
    
      - name: Setup ccache
        if: matrix.targetos != 'win'
        uses: hendrikmuhs/ccache-action@v1.2
        
      - name: Setup CCL cache
        id: cache-ccl
        uses: actions/cache@v5
        with:
          path: .cache/ccl
          key: cclcache-${{ matrix.targetos }}-${{ github.ref_name }}
          
      - name: Prepare environment
        shell: bash
        run: |
          .github/ci/${{matrix.targetos}}/prepare_sdk_environment.sh
          
      - name: Prepare workingcopy
        shell: bash
        run: |
          .github/ci/shared/prepare_workingcopy.sh ${{github.run_number}}
      
      - name: Fix Linux Arm64 build
        if: ${{ matrix.targetos == 'linux' }}
        shell: bash
        run: |
          cd framework
          git apply ../patches/linux-vulkan.patch
        
      - name: Build CCL tools
        if: ${{ matrix.targetos == 'linux' }}
        shell: bash
        run: |
          cd development/cmake
          cmake -B build/tools --fresh --preset linux-release -DBUILD_tools=ON ${CMAKE_BUILD_OPTIONS} \
            -DVENDOR_BUILDOUTPUT_DIRECTORY=${GITHUB_WORKSPACE}/framework/tools/bin/linux/ccl/x86_64 \
            -DVENDOR_CACHE_DIRECTORY=${GITHUB_WORKSPACE}/.cache/ccl
          cd build/tools
          cmake --build . --target cclpackage
          cmake --build . --target crypt
                    
      - name: Configure CMake
        shell: bash
        #env:
        #  ccl_SIGNING_AZURE_SECRET: ${{ secrets.SIGNING_AZURE_SECRET }}
        run: |
          cd development/cmake
          cmake -B build/sdk \
            --fresh --preset ${CMAKE_PRESET} \
            -DBUILD_sdk=ON \
            -DVENDOR_CACHE_DIRECTORY=${GITHUB_WORKSPACE}/.cache/ccl \
            ${CMAKE_BUILD_OPTIONS}
          
      - name: Build
        shell: bash
        run: |
          cd development/cmake/build/sdk          
          cmake --build . --config Debug
          cmake --build . --config Release
         
      - name: Sign Binaries
        if: matrix.signbinaries
        shell: bash
        run: |
          cd development/cmake/build/sdk          
          cmake --build . --config Debug --target sign_ccl_binaries
          cmake --build . --config Release --target sign_ccl_binaries
          
      - name: Package
        shell: bash
        run: |
          cd development/cmake/build/sdk    
          cpack -C 'Debug;Release' --config SdkPackageConfig.cmake ${CPACK_OPTIONS}
          
      - name: Sign Package
        if: matrix.signbinaries
        shell: bash
        run: |
          cd development/cmake/build/sdk          
          cmake --build . --config Release --target signed_sdkpackage
          
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ccl-sdk-${{matrix.targetos}}
          path: |
            build/cmake/archive/*.gz
            build/cmake/archive/*.sh
