name: CCL Tools for Linux

concurrency:
  group: ccl-tools-linux
  
on: workflow_call
  
jobs:
  build:
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: ubuntu-latest
            image: ccl-linux-base:22.04
            targetos: linux
    
    runs-on: ${{matrix.host}}
    
    permissions:
      contents: read
      packages: read
      
    container:
      image: ghcr.io/cclsoftware/${{matrix.image}}
      credentials:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
        
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
    
      - name: Prepare build environment
        uses: ./.github/ci/linux/prepare-build-environment
        with:
          targetos: ${{ matrix.targetos }}
    
      - name: Build CCL Tools
        shell: bash
        run: |
          export CMAKE_BUILD_OPTIONS="${CMAKE_BUILD_OPTIONS:-} -DBUILD_tools=ON -DCPACK_STRIP_FILES=ON"
          source ${GITHUB_WORKSPACE}/.github/ci/${{ matrix.targetos }}/configure_cmake_project.sh
          cd ${BUILD_DIR} 
          source ${GITHUB_WORKSPACE}/.github/ci/${{ matrix.targetos }}/build_cmake_target.sh
        env:
          BUILD_DIR: "build/tools"
          BUILD_CONFIG: Release
          CPACK_TARGET: archive
       
      - name: Build CCL Public Tools
        shell: bash
        run: |
          export CMAKE_BUILD_OPTIONS="${CMAKE_BUILD_OPTIONS:-} -DBUILD_public_tools=ON -DCPACK_STRIP_FILES=ON"
          source ${GITHUB_WORKSPACE}/.github/ci/${{ matrix.targetos }}/configure_cmake_project.sh
          cd ${BUILD_DIR}
          source ${GITHUB_WORKSPACE}/.github/ci/${{ matrix.targetos }}/build_cmake_target.sh
        env:
          BUILD_DIR: "build/publictools"
          BUILD_CONFIG: Release
          CPACK_TARGET: publictoolspackage
       
      - name: Build Core Tools
        shell: bash
        run: |
          export CMAKE_BUILD_OPTIONS="${CMAKE_BUILD_OPTIONS:-} -DBUILD_core_tools=ON -DCPACK_STRIP_FILES=ON"
          source ${GITHUB_WORKSPACE}/.github/ci/${{ matrix.targetos }}/configure_cmake_project.sh
          cd ${BUILD_DIR}
          source ${GITHUB_WORKSPACE}/.github/ci/${{ matrix.targetos }}/build_cmake_target.sh
        env:
          BUILD_DIR: "build/coretools"
          BUILD_CONFIG: Release
          CPACK_TARGET: package
       
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ccl-tools-${{matrix.targetos}}
          path: |
            build/cmake/archive/*.zip
