name: CCL Tools for Windows

concurrency:
  group: ccl-tools-win
  
on: workflow_call
  
jobs:
  build:
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: windows-2025
            image: ccl-win-base:latest
            targetos: win
            
    runs-on: ${{ matrix.host }}
    
    permissions:
      contents: read
      packages: read
      
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
  
      - name: Prepare build environment
        uses: ./.github/ci/win/prepare-build-environment
        with:
          image: ${{ matrix.image }}
          targetos: ${{ matrix.targetos }}
    
      - name: Build CCL Tools in container
        uses: ./.github/ci/win/build-cmake-target
        with:
          image: ${{ matrix.image }}
          signkeyvault: ${{ secrets.SIGNING_AZURE_KEYVAULT_WIN }}
          signclientid: ${{ secrets.SIGNING_AZURE_CLIENTID_WIN }}
          signtenantid: ${{ secrets.SIGNING_AZURE_TENANTID_WIN }}
          signcert: ${{ secrets.SIGNING_CERTIFICATE_WIN }}
          signserver: ${{ vars.SIGNING_TIMESTAMP_SERVER_WIN }}
          signsecret: ${{ secrets.SIGNING_AZURE_SECRET_WIN }}
          dockerargs: |
            -e BUILD_REVISION="${{ github.run_number }}" \
            -e BUILD_DIR="build/tools" \
            -e CMAKE_BUILD_OPTIONS="-DBUILD_tools=ON" \
            -e CPACK_TARGET="archive" \
       
      - name: Build CCL Public Tools in container
        uses: ./.github/ci/win/build-cmake-target
        with:
          image: ${{ matrix.image }}
          signkeyvault: ${{ secrets.SIGNING_AZURE_KEYVAULT_WIN }}
          signclientid: ${{ secrets.SIGNING_AZURE_CLIENTID_WIN }}
          signtenantid: ${{ secrets.SIGNING_AZURE_TENANTID_WIN }}
          signcert: ${{ secrets.SIGNING_CERTIFICATE_WIN }}
          signserver: ${{ vars.SIGNING_TIMESTAMP_SERVER_WIN }}
          signsecret: ${{ secrets.SIGNING_AZURE_SECRET_WIN }}
          dockerargs: |
            -e BUILD_REVISION="${{ github.run_number }}" \
            -e BUILD_DIR="build/publictools" \
            -e CMAKE_BUILD_OPTIONS="-DBUILD_public_tools=ON" \
            -e CPACK_TARGET="publictoolspackage" \
            
      - name: Build Core Tools in container
        uses: ./.github/ci/win/build-cmake-target
        with:
          image: ${{ matrix.image }}
          signkeyvault: ${{ secrets.SIGNING_AZURE_KEYVAULT_WIN }}
          signclientid: ${{ secrets.SIGNING_AZURE_CLIENTID_WIN }}
          signtenantid: ${{ secrets.SIGNING_AZURE_TENANTID_WIN }}
          signcert: ${{ secrets.SIGNING_CERTIFICATE_WIN }}
          signserver: ${{ vars.SIGNING_TIMESTAMP_SERVER_WIN }}
          signsecret: ${{ secrets.SIGNING_AZURE_SECRET_WIN }}
          dockerargs: |
            -e BUILD_REVISION="${{ github.run_number }}" \
            -e BUILD_DIR="build/coretools" \
            -e CMAKE_BUILD_OPTIONS="-DBUILD_core_tools=ON" \
            -e CPACK_TARGET="package" \
       
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ccl-tools-${{matrix.targetos}}
          path: |
            build/cmake/archive/*.zip
