name: CCL SDK for Mac and iOS

defaults:
  run:
    shell: bash

on: workflow_call

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: macos-15
            targetos: mac

    runs-on: ${{matrix.host}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Output status
        run: |
          echo "Runner: $RUNNER_NAME"
          echo "OS: $RUNNER_OS"
          echo "Image: $ImageOS"
          echo "Hostname: $(hostname)"
          echo "User: $(whoami)"
          pwd

      # - name: Fix macOS SDK
      #   run: |
      #     cd framework
      #     git apply ../patches/macos-sdk.patch

      - name: Setup CCL cache
        id: cache-ccl
        uses: actions/cache@v5
        with:
          path: .cache/ccl
          key: cclcache-${{ matrix.targetos }}-${{ github.ref_name }}

      - name: Prepare environment
        env:
          SIGNING_TEAMID_MAC: ${{ vars.SIGNING_TEAMID_MAC }}
          SIGNING_TEAMID_IOS: ${{ vars.SIGNING_TEAMID_IOS }}
          SIGNING_CERTIFICATE_MAC: ${{ vars.SIGNING_CERTIFICATE_MAC }}
        run: |
          .github/ci/${{matrix.targetos}}/prepare_sdk_environment.sh

      - name: Prepare workingcopy
        run: |
          .github/ci/shared/prepare_workingcopy.sh ${{github.run_number}}

      - name: Build
        env:
          APPLE_DEVELOPERID_CERTIFICATE_BASE64: ${{ secrets.APPLE_DEVELOPERID_CERTIFICATE_BASE64 }}
          APPLE_DEVELOPERID_CERTIFICATE_P12_PASSWORD: ${{ secrets.APPLE_DEVELOPERID_CERTIFICATE_P12_PASSWORD }}
          APPLE_DEVELOPMENT_CERTIFICATE_BASE64: ${{ secrets.APPLE_DEVELOPMENT_CERTIFICATE_BASE64 }}
          APPLE_DEVELOPMENT_CERTIFICATE_P12_PASSWORD: ${{ secrets.APPLE_DEVELOPMENT_CERTIFICATE_P12_PASSWORD }}
          APPLE_DISTRIBUTION_CERTIFICATE_BASE64: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE_BASE64 }}
          APPLE_DISTRIBUTION_CERTIFICATE_P12_PASSWORD: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE_P12_PASSWORD }}
          APPLE_KEYCHAIN_PASSWORD: ${{ secrets.APPLE_KEYCHAIN_PASSWORD }}
          APPLE_API_KEY_BASE64: ${{ secrets.APPLE_API_KEY_BASE64 }}
          APPLE_API_KEY_FILENAME: ${{ vars.APPLE_API_KEY_FILENAME }}
          APPLE_API_KEYID: ${{ vars.APPLE_API_KEYID }}
          APPLE_API_ISSUER: ${{ vars.APPLE_API_ISSUER }}
        run: |
          .github/ci/mac/setup_keychain.sh
          .github/ci/mac/configure_system.sh
          .github/ci/mac/build_sdk.sh

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ccl-sdk-${{matrix.targetos}}
          path: |
            build/deployment/mac/*.*