name: CCL SDK for Windows

concurrency:
  group: ccl-sdk-win
  
on: workflow_dispatch
  
jobs:
  build:
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: windows-2025
            image: ccl-win-sdk:latest
            targetos: win
            signbinaries: true
            
    runs-on: ${{matrix.host}}
    
    permissions:
      contents: read
      packages: read
      
    steps:
    
      - name: Log into registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Pull container
        shell: bash
        run: |
          docker pull ghcr.io/cclsoftware/${{matrix.image}}
          
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
    
      - name: Setup CCL cache
        id: cache-ccl
        uses: actions/cache@v5
        with:
          path: .cache/ccl
          key: cclcache-${{ matrix.targetos }}-${{ github.ref_name }}
          
      - name: Build in container
        shell: bash
        run: |
          #echo "DOCKERCMD=docker run --volume '"${{github.workspace}}:F:"' --workdir '"F:\\"' ghcr.io/cclsoftware/${{matrix.image}} bash -c" >> "$GITHUB_ENV"
          docker run --volume "${{github.workspace}}:F:" --workdir "F:\\" ghcr.io/cclsoftware/${{matrix.image}} bash -c \
            && echo "-- Prepare Build Environment"
            && .github/ci/${{matrix.targetos}}/prepare_sdk_environment.sh \
            && .github/ci/shared/prepare_workingcopy.sh ${{github.run_number}} \
            \
            && echo "-- Configure CMake Project" \
            && cd development/cmake \
            && cmake -B build/sdk --fresh --preset ${CMAKE_PRESET} -DBUILD_sdk=ON -DVENDOR_CACHE_DIRECTORY=/f/.cache/ccl ${CMAKE_BUILD_OPTIONS} \
            \
            && echo "-- Build Debug and Release" \
            && cd build/sdk && cmake --build . --config Debug && cmake --build . --config Release \
            \
            && echo "-- Sign Binaries" \
            && cmake --build . --config Debug --target sign_ccl_binaries && cmake --build . --config Release --target sign_ccl_binaries \
            \
            && echo "-- Build Installer" \
            && cpack -C "Debug;Release" --config SdkPackageConfig.cmake ${CPACK_OPTIONS} \
            \
            && echo "-- Sign Installer" \
            && cmake --build . --config Release --target signed_sdkpackage 
          
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ccl-sdk-${{matrix.targetos}}
          path: |
            build/cmake/archive/*.*
