name: CCL Tools for Mac

concurrency:
  group: ccl-tools-mac

defaults:
  run:
    shell: bash

on: workflow_dispatch

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: macos-15
            targetos: mac

    runs-on: ${{matrix.host}}

    steps:
      - name: Run build script
        uses: ./.github/ci/mac/execute-build-script
        with:
          image: build_tools.sh

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ccl-tools-${{matrix.targetos}}
          path: |
            build/deployment/mac/*.*