name: CCL SDK

concurrency:
  group: ccl-sdk
  
permissions:
  contents: read
  packages: read
  actions: read

on: 
  workflow_dispatch:
    inputs:
      buildWin:
        description: 'Build Windows SDK'
        type: boolean
        required: true
        default: true
      buildMac:
        description: 'Build Mac SDK'
        type: boolean
        required: true
        default: true
      buildLinux:
        description: 'Build Linux SDK'
        type: boolean
        required: true
        default: true
      buildAndroid:
        description: 'Build Android SDK'
        type: boolean
        required: true
        default: true

jobs:

  build-documentation:
    uses: ./.github/workflows/ccl-sdk-documentation.yml
    secrets: inherit

  build-android-sdk:
    if: ${{ inputs.buildAndroid }}
    uses: ./.github/workflows/ccl-sdk-android.yml
    permissions:
      contents: read
      packages: read
      actions: read
    secrets: inherit

  build-linux-sdk:
    if: ${{ inputs.buildLinux }}
    needs: [build-android-sdk, build-documentation]
    uses: ./.github/workflows/ccl-sdk-linux.yml
    with:
      docartifact: ${{ needs.build-documentation.outputs.artifact-id }}
      androidartifact: ${{ needs.build-android-sdk.outputs.artifact-id }}
    permissions:
      contents: read
      packages: read
      actions: read
    secrets: inherit
    
  build-windows-sdk:
    if: ${{ inputs.buildWin }}
    needs: [build-android-sdk, build-documentation]
    uses: ./.github/workflows/ccl-sdk-win.yml
    with:
      docartifact: ${{ needs.build-documentation.outputs.artifact-id }}
      androidartifact: ${{ needs.build-android-sdk.outputs.artifact-id }}
    permissions:
      contents: read
      packages: read
      actions: read
    secrets: inherit
    
  build-macos-sdk:
    if: ${{ inputs.buildMac }}
    needs: [build-android-sdk, build-documentation]
    with:
      docartifact: ${{ needs.build-documentation.outputs.artifact-id }}
      androidartifact: ${{ needs.build-android-sdk.outputs.artifact-id }}
    uses: ./.github/workflows/ccl-sdk-mac.yml
    secrets: inherit
