name: CCL SDK for Windows

concurrency:
  group: ccl-sdk-win
  
on: workflow_call
  
jobs:
  build:
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: windows-2025
            image: ccl-win-sdk:latest
            targetos: win
            
    runs-on: ${{ matrix.host }}
    
    permissions:
      contents: read
      packages: read
      
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
    
      - name: Prepare build environment
        uses: ./.github/ci/win/prepare-build-environment
        secrets: inherit
        with:
          image: ${{ matrix.image }}
          targetos: ${{ matrix.targetos }}
    
      - name: Build in container
        shell: bash
        run: |
          docker run \
            --volume "${{ github.workspace }}:F:" \
            --workdir "F:\\" \
            -e ccl_SIGNING_AZURE_KEYVAULT_WIN="${{ secrets.SIGNING_AZURE_KEYVAULT_WIN }}" \
            -e ccl_SIGNING_AZURE_CLIENTID_WIN="${{ secrets.SIGNING_AZURE_CLIENTID_WIN }}" \
            -e ccl_SIGNING_AZURE_TENANTID_WIN="${{ secrets.SIGNING_AZURE_TENANTID_WIN }}" \
            -e ccl_SIGNING_CERTIFICATE_WIN="${{ secrets.SIGNING_CERTIFICATE_WIN }}" \
            -e ccl_SIGNING_TIMESTAMP_SERVER_WIN="${{ vars.SIGNING_TIMESTAMP_SERVER_WIN }}" \
            -e ccl_SIGNING_AZURE_SECRET="${{ secrets.SIGNING_AZURE_SECRET_WIN }}" \
            -e BUILD_REVISION="${{ github.run_number }}" \
            ghcr.io/cclsoftware/${{ matrix.image }} \
            bash ./.github/ci/win/build_sdk.sh
          
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ccl-sdk-${{matrix.targetos}}
          path: |
            build/cmake/archive/*.exe
